USE [dbFacility]
GO

/****** Object:  Table [dbo].[Ramo]    Script Date: 18/02/2022 16:19:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ramo](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ramo] [nvarchar](2) NULL,
	[descricao] [nvarchar](200) NULL,
 CONSTRAINT [PK_Ramo_Id] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

